### ISSUE TITLE
Other categories of devices

### ISSUE THREAD

**Issue by Venger2005** [sebmos/homebridge-eufy#2]
Hi there.  Does your homebridge plug-in support the Eufy line of Wi-Fi enabled vacuum cleaners?  Even if it did, would there be any merit in exposing them to Homekit as I'm not sure what level of functionality would then be displayed in a homekit app?  Thanks.

**Comment by sebmos** [comment]
Hey @Venger2005,

The homebridge-eufy plug-in itself doesn't support Eufy's vacuum cleaners. I don't own one of them, so I couldn't add support anyway. I would be happy to look at contributions that add that functionality.

But as you seem to already suspect, HomeKit doesn't actually support vacuum cleaners. I saw a plug-in for WiFi Roombas that treats them as a switch - which at least lets you know whether it is on or not - but that's it.

**Comment by joshstrange** [comment]
I'll be interested in contributing to this when I get my Eufy vacuum cleaner and play with it a little. I think something [like this](https://www.npmjs.com/package/homebridge-xiaomi-mi-robot-vacuum), [this](https://www.npmjs.com/package/homebridge-irobot-roomba), [or this](https://www.npmjs.com/package/homebridge-neato) will be good inspiration for how to expose the functionality since vacuums aren't directly supported.

As long as the API returns them and they are controllable in similar ways to the other Eufy stuff I bet it won't be too terrible. That said it [looks like it uses a TuyaAPI interface](https://github.com/google/python-lakeside/issues/16) and I've had issues with that in the past since the only way I could make it work was to let homebridge take over the device 100% and remove it from the main app (SmartLife and thus Alexa).

I bought the [15C](https://smile.amazon.com/gp/product/B07H3JNDL5/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) (It's on sale today for just $180, normally $250) and I want it to be controllable by Alexa (it is out of the box) AND HomeKit (which as I mentioned above might be tricky if I can't sniff the TuyaAPI token off my iOS device or control it some other way).

**Comment by sebmos** [comment]
Hey @joshstrange,

Cool - let me know how it's going! Let me know if you run into any issues I can help with with the homebridge stuff - I still don't have a Eufy vacuum myself, so can't help with debugging/testing.

**Comment by joshstrange** [comment]
@sebmos Ok, I am able to control my RoboVac using a [python library](https://github.com/mitchellrj/eufy_robovac) and using the Tuyapi nodeJS library I can talk to my vacuum cleaner. I'm a little worried that trying to integrate it into your existing library might be a little more than I want to take on. 

Part of that is due to the fact the it used the Tuya API instead of protobuf and also because it's in a whole different world of type of device. I don't want to fall into a square-peg-round-hole situation.

My thought is I will look at how the other robot vacuum cleaner homebridge plugins are doing it ([see examples here](https://github.com/sebmos/homebridge-eufy/issues/2#issuecomment-489707676)) and reuse a lot of their code. If the one I want to base most my work on does use an external library for all the command/control of the device and is just a wrapper (similar-ish to how you split out a separate node lib for control the devices) then I will do the same and you are more than welcome to use it within your plugin here.

I don't have a lot of desire to maintain a HB plugin long-term and really would like to write just enough code to get my vacuum to work and then step away after contributing that code. What I'm trying to say is I may publish a homebridge-eufy-robovac (or similarly named) HB plugin but if you (or anyone else) wants to merge/pull request/borrow/steal all the code to make it better or combine it with yours I am 100% on board. 

Also it's complicated because you (@sebmos) have lights and no RoboVac and I have a RoboVac and no lights (and no plans to get them as I'm happy with my zigbee lights and z-wave switches) so either of us trying to merge these libraries is going to be hard as we might break the other class of device without know. 

Anyways, no matter what I do I will publish anything I accomplish and post back here for you or anyone else who is interested.

**Comment by sebmos** [comment]
Makes sense, really curious to hear how it goes!

**Comment by joshstrange** [comment]
@sebmos @Venger2005 Just wanted to give you an update:

I have a published npm package that can control my RoboVac 15C (I have no reason to suspect it can only control the 15C and I believe the person I got most of my code from has a 30C). You can find the repo here: https://github.com/joshstrange/eufy-robovac

I still need to make a homebridge plugin but I wanted to get this out there now.

**Comment by Venger2005** [comment]
Thanks for the update. Been following the thread.  Let meet know when the homebridge plug-in is ready and will be happy to test.

**Comment by joshstrange** [comment]
@sebmos @Venger2005 I have finished my [homebridge plugin](https://www.npmjs.com/package/homebridge-eufy-robovac).

It's probably pretty sloppy but it works and I'm open to changes.
