### ISSUE TITLE
socket closed - attempting restart - ERROR

### ISSUE THREAD

**Issue by nathsea** [sebmos/homebridge-eufy#3]
hi,
i have recently installed your plugin, with some others. 
I then started to get an error socket closed - attempting restart in my log. I couldn't work it out, so i deleted all of my plugins, one at a time, until this one was left. I deleted yours and the error stopped I re-added it and the errors came back again.. 
It appears to poll and then just keeps reporting the error.
![Screenshot 2019-03-18 at 07 45 02](https://user-images.githubusercontent.com/48316013/54514347-cf438c80-4951-11e9-949d-81c881d57335.png)

**Comment by sebmos** [comment]
Hey @nathsea,

Those log messages from the underlying [`node-eufy-api`](http://github.com/sebmos/node-eufy-api) package are a bit misleading - the device has indeed closed the socket, and homebridge is restarting the connection again (successfully - otherwise there would be a separate error message.)

You don't have to worry about those log messages, but I'll address them in a future update.

**Comment by nathsea** [comment]
Hi !
Thanks for your response. That puts my mind at ease. I look forward to not seeing them in my logs though :) 
Cheers
Nath

**Comment by sebmos** [comment]
Hey @nathsea,

The 0.3.0 update should resolve this issue - warnings won't be reported anymore, and the devices won't automatically re-connect anymore, either. (It's not really necessary, anyway.)

**Comment by nathsea** [comment]
@sebmos thanks will give it a try 👍

**Comment by nathsea** [comment]
Hi @sebmos
Since this update I have been having huge issues with the switches dropping off of home. Is this to do with them not automatically re-connecting ? 

Nath
